stages:
- build
- test
- deploy

build:
stage: build
image: python:3.12.5
script:
- pip install -r requirements.txt

test:
stage: test
image: python:3.12.5
script:
- pip install -r requirements.txt
- pytest

deploy:
stage: deploy
image: python:3.12.5
script:
- echo "Deploying your project here"